### ISSUE TITLE
Add a custom profile for AOT compilation

### ISSUE THREAD

**Issue by irongut** [irongut/XF40Demo#31]
Enabling profiled AOT using the default profile improves the launch time of the app by approx half a second (22%). With Visual Studio 2019 v16.5 Preview MSBuild can now create a custom profile to improve this further.

* Generate a custom AOT profile.
* Compare launch time improvement vs default profile and no AOT.
* Compare app size increase vs default profile and no AOT.

### References
[VS2019 16.5 Preview Blog](https://devblogs.microsoft.com/xamarin/visual-studio-2019-version-16-5-preview-2/)
[Custom Profiled AOT Docs](https://github.com/xamarin/xamarin-android/blob/master/Documentation/guides/profiling.md#profiling-the-aot-compiler)
#5 - Enable Profiled AOT
irongut/EliteALD#79 Add a custom startup profile for AOT compilation

**Comment by irongut** [comment]
[VS2019 v16.5 Release - Xamarin blog](https://devblogs.microsoft.com/xamarin/whats-new-for-xamarin-developers-in-visual-studio-2019-version-16-5/)

**Comment by irongut** [comment]
[Using Custom AOT Profiles with Xamarin.Android - Ryan Davis](https://ryandavis.io/using-custom-aot-profiles-with-xamarin-android/)
[Xamarin Blog: Faster Application Startup using Custom Profiles with Startup Tracing on Android](https://devblogs.microsoft.com/xamarin/faster-android-startup-times-with-startup-tracing/)

**Comment by irongut** [comment]
## Custom Profile Process

1. Delete any existing profile and empty the recycle bin.
2. Add to PATH: `C:\Program Files (x86)\Android\android-sdk\platform-tools`
2. Use VS Developer Command Prompt run as Admin (run Windows Terminal as Admin).
3. Change to your Android project’s directory that contains the .csproj.
3. To start profiling: `msbuild -t:Rebuild -p:Configuration=Release /t:BuildAndStartAotProfiling`
4. To stop profiling: `msbuild /t:FinishAotProfiling`
5. Include the file `custom.aprof` in the Android project and set its build action to `AndroidAotProfile`.
6. Edit the Android project file as below.

If you get an error when you stop profiling either the Android SDK is not in the path, the command prompt is not elevated or the profile file exists already.

Android csproj changes:

```xml
<PropertyGroup>
    <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot> 
    <AndroidUseDefaultAotProfile>false</AndroidUseDefaultAotProfile>
</PropertyGroup>
```

_Originally posted by @irongut in https://github.com/irongut/EliteALD/issues/79#issuecomment-864321010_

**Comment by irongut** [comment]
```
D:\Dev\Csharp\Demos\XF40Demo\XF40Demo\XF40Demo.Android>msbuild /t:FinishAotProfiling
Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 14/08/2021 20:53:48.
Project "D:\Dev\Csharp\Demos\XF40Demo\XF40Demo\XF40Demo.Android\XF40Demo.Android.csproj" on node 1 (FinishAotProfiling target(s)).
FinishAotProfiling:
  "adb"  forward tcp:9999 tcp:9999
  9999
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\aprofutil"  -s -v -p 9999 -o "custom.aprof"
  Reading from '127.0.0.1:9999'...
  Read total 0 bytes...
EXEC : error : aprofutil: Unable to read profile through local port: 9999. [D:\Dev\Csharp\Demos\XF40Demo\XF40Demo\XF40Demo.Android\XF40Demo.Android.csproj]
  System.IO.IOException: Input file is too small.
     at Mono.Profiler.Aot.ProfileReader.ReadAllData(Stream stream)
     at aotprofiletool.MainClass.ReadProfileFromPort(ProfileReader reader)
     at aotprofiletool.MainClass.Main(String[] args)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Application.targets(53,5): error MSB3075: The command ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\aprofutil"  -s -v -p 9999 -o "custom.aprof"" exited with code 5. Please verify that you have sufficient rights to run this command. [D:\Dev\Csharp\Demos\XF40Demo\XF40Demo\XF40Demo.Android\XF40Demo.Android.csproj]
Done Building Project "D:\Dev\Csharp\Demos\XF40Demo\XF40Demo\XF40Demo.Android\XF40Demo.Android.csproj" (FinishAotProfiling target(s)) -- FAILED.
```

This is the same error as irongut/EliteALD#376 Regenerate AOT Profile, so is not related to the previous profile and is an inability to retrieve the completed profile.
